### ISSUE TITLE
Seems I can't find this package on search in npm

### ISSUE THREAD

**Issue by jloveric** [mateogianolio/nlapack#1]
I've tried to search for this package on npm under lapack and nlapack and it doesn't show up - should it?  Seems like you need some additional keywords on npm or maybe it's being pulled from another repo?  At any rate, the top search for npm lapack produces a version that uses the ffi interface, which should be much slower than this one.

**Comment by mateogianolio** [comment]
Hey! I did not want to publish it because it is a work in progress, the test suite is bad and writing the test suite requires very extensive knowledge of linear algebra. I would appreciate if you can point me to resources with examples of LAPACK operations.

You are right that the ffi interface is much slower and that was part of the reason I started working on this library. Another reason is that completing this means that we are one step closer to being able to implement a high performance linear algebra library in Node.js similar to numpy.

I'm hopeful I will finish some day, but it will take time.

**Comment by mateogianolio** [comment]
Now that I think about it, the LAPACK bindings could actually be tested using scipy's LAPACK wrappers (see https://docs.scipy.org/doc/scipy/reference/linalg.lapack.html)

**Comment by mateogianolio** [comment]
https://github.com/scipy/scipy/tree/master/scipy/linalg/tests

**Comment by mateogianolio** [comment]
Just uploaded 0.1.0: https://www.npmjs.com/package/nlapack
